# Generated by Django 5.0.2 on 2024-06-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=50)),
                ('user_emissions', models.CharField(default='20', max_length=50)),
                ('user_country', models.CharField(default='20', max_length=50)),
                ('water_emissions', models.CharField(default='20', max_length=50)),
                ('user_email', models.CharField(default='default@email.com', max_length=50)),
            ],
        ),
    ]
