# Generated by Django 5.0.2 on 2024-06-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdata_first_name_userdata_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(default='JohnDoe', max_length=50),
        ),
    ]
