# Generated by Django 5.0.2 on 2024-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userdata_first_name_remove_userdata_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_tier',
            field=models.CharField(default='Free account', max_length=50),
        ),
    ]
