# Generated by Django 5.0.2 on 2024-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userdata_user_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=50)),
                ('volunteer_email', models.CharField(max_length=50)),
                ('volunteer_place', models.CharField(max_length=50)),
                ('volunteer_id', models.CharField(max_length=50)),
            ],
        ),
    ]
