# Generated by Django 5.0.2 on 2024-07-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_cartype',
            field=models.CharField(default='electric', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_daily_commute',
            field=models.CharField(default='50km', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_diet',
            field=models.CharField(default='vegan', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_energytype_use',
            field=models.CharField(default='grid', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_household_pop',
            field=models.CharField(default='3', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_travel_freq',
            field=models.CharField(default='2', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_ventilation_type',
            field=models.CharField(default='gas', max_length=50),
        ),
    ]
