# Generated by Django 5.0.2 on 2024-07-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userdata_user_cartype_userdata_user_daily_commute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_name',
        ),
    ]
