# Generated by Django 5.0.2 on 2024-07-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_userdata_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(default='JohnDoe', max_length=50),
        ),
    ]
