# Generated by Django 5.0.2 on 2024-07-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userdata_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_city',
            field=models.CharField(default='Verdeius', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_ip',
            field=models.CharField(default='127.0.0.1', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_region',
            field=models.CharField(default='Verde', max_length=50),
        ),
    ]
