# Generated by Django 5.0.2 on 2024-07-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userdata_user_city_userdata_user_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_actualcountry',
            field=models.CharField(default='Verde gh', max_length=50),
        ),
    ]
