# Generated by Django 5.0.2 on 2024-07-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userdata_user_actualcountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_about',
            field=models.CharField(default="I'm crazy for the climate.", max_length=100),
        ),
    ]
