# Generated by Django 5.0.2 on 2024-07-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_userdata_user_name_userdata_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_offset',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
