# Generated by Django 5.0.2 on 2024-07-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userdata_user_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_actualcountry',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_city',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_region',
        ),
    ]
