# Generated by Django 5.0.2 on 2024-07-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_volunteerevents_delete_volunteer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='number_events',
            new_name='events_attended',
        ),
        migrations.AddField(
            model_name='userdata',
            name='projects_funded',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
