# Generated by Django 5.0.2 on 2024-07-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_number_events_userdata_events_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevents',
            name='event_organiser',
            field=models.CharField(default='Paradio', max_length=50),
        ),
    ]
