# Generated by Django 5.0.2 on 2024-07-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_volunteerevents_event_organiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevents',
            name='event_date',
            field=models.CharField(default='20/04/2303', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteerevents',
            name='event_location',
            field=models.CharField(default='San francisco', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteerevents',
            name='orientation_date',
            field=models.CharField(default='20/04/2003', max_length=50),
        ),
    ]
