# Generated by Django 5.0.2 on 2024-08-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_volunteerevents_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='prev_user_emissions',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_airtravel_percentage',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_car_percentage',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_diet_percentage',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_house_percentage',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_emissions',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='water_emissions',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
