# Generated by Django 5.0.2 on 2024-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_userdata_prev_user_emissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='prev_user_emissions',
            new_name='prev_user_emissions1',
        ),
        migrations.AddField(
            model_name='userdata',
            name='prev_user_emissions2',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='prev_user_emissions3',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
