# Generated by Django 5.0.2 on 2024-08-06 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_rename_prev_user_emissions_userdata_prev_user_emissions1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='VerdeiaInfo',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_travel_freq',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50)),
                ('user_events', models.CharField(max_length=50)),
                ('user_location', models.CharField(max_length=50)),
                ('user_date', models.CharField(max_length=50)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
