# Generated by Django 5.0.2 on 2024-08-06 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_rename_newsletter_verdeiainfo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerdeiaInfo',
            new_name='Newsletter',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
