# Generated by Django 5.0.2 on 2024-08-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_rename_verdeiainfo_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_username',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='UserEvents',
        ),
    ]
