# Generated by Django 5.0.2 on 2024-08-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_event',
            name='name',
            field=models.CharField(default='hello', max_length=100),
        ),
    ]
