# Generated by Django 5.0.2 on 2024-08-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_event',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
