# Generated by Django 5.0.2 on 2024-08-07 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_user_event_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Event',
            new_name='UserEvent',
        ),
    ]
