# Generated by Django 5.0.2 on 2024-08-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_userevent_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='volunteer_id',
        ),
        migrations.RemoveField(
            model_name='volunteerevents',
            name='event_place',
        ),
        migrations.AddField(
            model_name='volunteerevents',
            name='event_url',
            field=models.CharField(default="{% url 'event' %}", max_length=50),
        ),
    ]
