# Generated by Django 5.0.2 on 2024-08-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_userdata_active_goals_userdata_goals_finished_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGoal',
        ),
    ]
